### PR TITLE
Goldberg-Tarjan's Cost-Scaling

### PR DESCRIPTION
**Pull request by Lagrang3**
We are implementing the Cost-Scaling algorithm described in [1] and [2] section 10.3

In this first commit we have the generic version, which has a theoretical complexity of O(n^2 m log (nC)), which is an improvement with respect to Capacity-Scaling, that scales like O((m log U)(m + n log n).

[1] Andrew V. Goldberg, Robert E. Tarjan, (1990) Finding Minimum-Cost Circulations by Successive Approximation. Mathematics
of Operations Research 15(3):430-466. http://dx.doi.org/10.1287/moor.15.3.430 

[2] Ahuja, Magnanti, Orlin, Network Flows 1993.

### CODE REVIEW

**Comment by Lagrang3** [comment]
The implementation seems to be corrects.

**Comment by Lagrang3** [comment]
We have performed some benchmarks. The time bounds of the new Cost-scaling are better than Capacity-scaling, and we can move to bigger graphs benchmarks if we discard Capacity-scaling. At his point we can run in networks with 2^14 = 16'000 nodes in 2 seconds. Still Ortools has better runtime, with 0.1 seconds in the worst case. Yet we have done an improvement of orders of magnitude with respect to Capacity-scaling.
Notice that Capacity-Scaling and Cost-Scaling are the only Polynomial Min-Cost-Flow solvers that our library provides, hence I am not working anymore in optimizing the Min-Cost-Augmenting-Path (Edmond-Karp) and Primal-Dual algorithms.
The next task we have ahead is to reduce the time complexity of Cost-scaling either by implementing a Dual-scaling algorithm or the Cost-scaling with dynamic trees.

latest

**Comment by Lagrang3** [comment]
In a denser network (m = 25*n, instead of m = 7.5*n) the Cost-scaling is orders of magnitude better than the pseudo-polynomial algorithms.
latest

**Comment by renepickhardt** [comment]
This is all very very exciting! Mining forward to see how you become competetive with ortools implementation but also have the uncertainty network API in your solver!

**Pull request merged**
